site_name: Backendless Pro Administrator Guide
nav:
- 'Overview': 'index.md'
- 'Installation':
  - 'General Requirements': 'requirements.md'
  - 'Community Edition': 'community-edition.md'
  - 'AWS':
    - 'Basic setup': 'install/cloud/aws.md'
    - 'Load balancer configuration': 'install/cloud/aws-nlb-configuration-for-letsencrypt.md'
  - 'Azure':
    - 'Basic setup': 'install/cloud/azure.md'
    - 'Load balancer configuration': 'install/cloud/azure-load-balancer.md'
  #- 'Digital Ocean': 'install/cloud/digitalocean.md'
  - 'Ubuntu': 'install/ubuntu.md'
  - 'Mac OS/Windows': 'install/mac-windows.md'
- Configuration:
  - configuration/index.md
  - 'Developer Registration Setttings': 'configuration/developer.md'
  - 'App Cloning/Export/Import': 'configuration/clone.md'
  - 'File Service Settings': 'configuration/file-service.md'
  - 'Database Service Settings': 'configuration/data-service.md'
  - 'MySQL Connection Settings': 'configuration/mysql-connection.md'
  - 'Mongo Connection Settings': 'configuration/mongo-connection.md'
  - 'Port description': 'configuration/ports.md'
#- 'Runtime and Operations':
#  - 'Logging': 'logging.mg'
#  - 'Backup': 'backup.md'
#- 'Upgrade':
#  - 'Single instance':
#    - 'Upgrade Backendless Pro': 'upgrade-single-instance.md'
#    - 'Upgrade Pro Manager': 'upgrade-pro-man.md'

docs_dir: content
site_dir: ../prod/backendless-pro-manager

copyright: 'Copyright &copy; 2024 Backendless Corp'

extra_css:
  - 'css/style.css'
# extra_css:
#  - 'css/style.css'
#  - 'css/newstyle.css'
#  - 'css/bootstrap.min.css'
#  - 'css/bootstrap-theme.min.css'
#  - 'css/tabs.css'
#  - 'css/docs.css'
#  - 'css/bootstrap-tour-standalone.min.css'
#  - 'css/materialoverride.css'

# extra_javascript:
#  - 'js/jquery-3.3.1.min.js'
#  - 'js/bootstrap-tour-standalone.min.js'
#  - 'js/docs.js'

theme:
  name: 'material'
  logo: 'backendlesslogo.png'
  custom_dir: '../theme'
  features:
    - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.tabs.link
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
  palette:
 #   - primary: white
    - scheme: white
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

use_directory_urls: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      linenums: False
      guess_lang: False
  - toc:
      permalink: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - abbr
plugins:
  - search
  - glightbox:
      skip_classes:
        - skip-lightbox
  - include-markdown:
      comments: false