site_name: Backendless Automations Guide
nav:
- 'Overview': 'index.md'
- 'Terminology': 'definitions.md'
- 'Flow Manager': 'flowmanager.md'
- 'Quick Start Guide': 'todo.md'
- 'Flow Management':
  - 'Creating New Flows': 'createflow.md' 
  - 'Renaming Flows' : 'renameflow.md'
  - 'Deleting Flows' : 'deleteflow.md'
  - 'Flow Permissions': 'callflowpermission.md'
  - 'Visual Customizations': 'flowappearance.md' 
  - 'Version Management' : 'versionmanagement.md'
  - 'Scheduled Flows' : 'scheduledflows.md'
  - 'Best Practices': 'bestpractices.md'
- 'Creating Flows' :
  - 'Flow Editor' : 'floweditor.md'
  - 'Working with Blocks' : 'workingwithblocks.md' 
  - 'Naming your Blocks' : 'blocknaming.md'
  - 'Data Movement in Flows' : 'dataflow.md'
  - 'Repeated Behavior (Loops)' : 'loops.md' 
  - 'Data Transformations' : 'todo.md'  
  - 'Expression Editor': 'todo.md'   
  - 'Implementing Delays': 'waitblock.md'  
  - 'Grouping Blocks' : 'todo.md'    
  - 'Variables and Data Buckets': 'todo.md'  
  - 'Error Handling': 'todo.md'  
  - 'Testing your Flows' : 'todo.md'
  - 'Custom Actions' : 'todo.md'  
- 'Running Flows' :
  - 'Service Level Agreements (SLAs)' : 'todo.md'   
  - 'Comliance' : 'todo.md'  
  - 'Analytics' : 'todo.md'  
- 'Block Reference' :
  - 'Triggers' : 
    - 'External Callback' : 'todo.md'  
    - 'Record Saved in Database' : 'todo.md'  
    - 'Record Removed in Database' : 'todo.md'  
    - 'App Logic Trigger' : 'todo.md'  
    - 'User Registered' : 'todo.md'
  - 'Actions' :
    - 'Send Email': 'todo.md'  
    - 'Save Record in Database': 'todo.md'  
    - 'Delete Record in Database': 'todo.md'  
    - 'Find Record(s) in Database': 'todo.md'  
    - 'Send Push Notification': 'todo.md'  
    - 'Run API Service': 'todo.md'  
    - 'Call Flow': 'todo.md'  
    - 'HTTP Request': 'todo.md'      
  - 'Conditions' :
    - 'Condition' : 'todo.md'  
    - 'Condition with Transformer' : 'todo.md'  
  - 'Groups' :
    - 'Triggers Group': 'todo.md'  
    - 'Actions Group' : 'todo.md'  
  - 'Utilities' :
    - 'Repeat While': 'todo.md'  
    - 'Wait': 'todo.md'  
    - 'Error Handler': 'todo.md'  
    - 'Set Variables': 'todo.md'  
    - 'Data Bucket': 'todo.md'  
    - 'Transform Data': 'todo.md'


   
docs_dir: content
site_dir: ../prod/automations

copyright: 'Copyright &copy; 2024 Backendless Corp'

# extra_css:
#  - 'css/style.css'
#  - 'css/newstyle.css'
#  - 'css/bootstrap.min.css'
#  - 'css/bootstrap-theme.min.css'
#  - 'css/tabs.css'
#  - 'css/docs.css'
#  - 'css/bootstrap-tour-standalone.min.css'
#  - 'css/materialoverride.css'

# extra_javascript:
#  - 'js/jquery-3.3.1.min.js'
#  - 'js/bootstrap-tour-standalone.min.js'
#  - 'js/docs.js'

theme:
  name: 'material'
  logo: 'backendlesslogo.png'
  features:
    - header.autohide
    - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.tabs.link
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
#    - navigation.sections
#    - navigation.expand
    - navigation.path
  custom_dir: 'overrides'
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode  

use_directory_urls: false

plugins:
  - glightbox
  - search

extra:
  generator: false

markdown_extensions:
  - admonition
  - codehilite:
      linenums: False
      guess_lang: False
  - toc:
      permalink: True
#  - markdown_fenced_code_tabs:
#      single_block_as_tab: False
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg    
  - attr_list    
