site_name: FlowRunnerâ„¢ User Guide
site_url: https://docs.flowrunner.ai
site_description: Comprehensive documentation for FlowRunner, a no-code platform for automating business processes with ease.

nav:
- 'Overview': 'index.md'
- 'Terminology': 'definitions.md'
- 'Flow Manager': 'flowmanager.md'
- 'Quick Start Guide': 'quickstart.md'
- 'Flow Management':
  - 'Creating Flows' : 'flow-management/createflow.md' 
  - 'Renaming Flows' : 'flow-management/renameflow.md'
  - 'Deleting Flows' : 'flow-management/deleteflow.md'
  - 'Flow Permissions': 'flow-management/callflowpermission.md'
  - 'Visual Customizations': 'flow-management/flowappearance.md' 
  - 'Version Management' : 'flow-management/versionmanagement.md'
  - 'Scheduled Flows' : 'flow-management/scheduledflows.md'
  - 'Best Practices': 'flow-management/bestpractices.md'
- 'Flow Editing' :
  - 'Flow Editor' : 'flow-editing/floweditor.md'
  - 'Working with Blocks' : 'flow-editing/workingwithblocks.md' 
  - 'Naming your Blocks' : 'flow-editing/blocknaming.md'
- 'Flow Development' :  
  - 'Data Movement in Flows' : 'flow-editing/dataflow.md'
  - 'Expression Editor': 'flow-editing/expressioneditor.md'   
  - 'Variables and Data Buckets': 'flow-editing/variables.md'  
  - 'Data Transformations' : 'flow-editing/transformer.md'  
  - 'Conditional Logic': 'flow-editing/conditions.md'
  - 'Implementing Delays': 'flow-editing/waitblock.md'  
  - 'Grouping Triggers' : 'flow-editing/grouping-triggers.md'    
  - 'Groupping Actions' : 'flow-editing/grouping-actions.md'
  - 'Repeated Behavior (Loops)' : 'flow-editing/loops.md' 
  - 'Error Handling': 'flow-editing/error-handling.md'  
  - 'AI Integration': 'flow-editing/using-ai.md'
  - 'PDF Generator': 'flow-editing/pdf-generator.md'
  - 'Testing your Flows' : 'flow-editing/testing.md'
  - 'Custom Actions' : 'flow-editing/custom-actions.md'  
- 'Extending FlowRunner' : 
   - 'About Extensibility' : 'extensibility/overview.md'
   - 'Custom Actions':
     - 'About Custom Actions': 'extensibility/custom-action.md'  
     - 'Quick Start Guide' : 'extensibility/actions-quick-start.md'
     - 'Action Development' : 'extensibility/action-development.md'
     - 'Service Config Params': 'extensibility/service-config.md'     
     - 'OAuth2 Authorization': 'extensibility/oauth2-services.md' 
     - 'Custom Action Testing': 'extensibility/action-testing.md'
- 'Running Flows' :
  - 'Launching Flows' : 'flow-execution/overview.md'
  - 'Service Level Agreements (SLAs)' : 'flow-execution/sla.md'   
  - 'Compliance' : 'flow-execution/compliance.md'  
  - 'Analytics' : 'flow-execution/analytics.md'  
- 'Block Reference' :
  - 'Triggers' : 
    - 'External Callback' : 'reference/external-callback-trigger.md'  
    - 'App Logic Trigger' : 'reference/applogic-trigger.md'  
    - 'Record Created in Database' : 'reference/record-saved-trigger.md'  
    - 'Record Updated in Database' : 'reference/record-updated-trigger.md'  
    - 'Record Removed in Database' : 'reference/record-removed-trigger.md'  
    - 'User Registered' : 'reference/user-registered-trigger.md'
  - 'Actions' :
    - 'Send Email': 'reference/send-email-action.md'  
    - 'Save Record in Database': 'reference/save-record-action.md'  
    - 'Delete Record in Database': 'reference/delete-record-action.md'  
    - 'Find Record(s) in Database': 'reference/find-records-action.md'  
    - 'Send Push Notification': 'reference/send-push-notification-action.md'  
    - 'AI Router': 'reference/ai-router-action.md'
    - 'Run API Service': 'reference/run-api-service-action.md'  
    - 'Call Flow': 'reference/call-flow-action.md'  
    - 'HTTP Request': 'reference/http-request-action.md'      
  - 'Conditions' :
    - 'Condition' : 'reference/condition.md'  
    - 'Condition with Transformer' : 'reference/condition-with-transformer.md'  
  - 'Groups' :
    - 'Triggers Group': 'reference/triggers-group.md'  
    - 'Actions Group' : 'reference/actions-group.md'  
  - 'Utilities' :
    - 'Repeat (Loops)': 'reference/repeat-loops.md'  
    - 'Wait': 'reference/wait.md'  
    - 'Error Handler': 'reference/error-handler.md'  
    - 'Set Variables': 'reference/set-variables.md'  
    - 'Transform Data': 'reference/transformer.md'

   
docs_dir: content
site_dir: ../prod/automations

copyright: 'Copyright &copy; 2024 Backendless Corp'

extra_css:
  - 'css/style.css'
#  - 'css/newstyle.css'
#  - 'css/bootstrap.min.css'
#  - 'css/bootstrap-theme.min.css'
#  - 'css/tabs.css'
#  - 'css/docs.css'
#  - 'css/bootstrap-tour-standalone.min.css'
#  - 'css/materialoverride.css'

# extra_javascript:
#  - 'js/jquery-3.3.1.min.js'
#  - 'js/bootstrap-tour-standalone.min.js'
#  - 'js/docs.js'

theme:
  name: 'material'
#  logo: 'flowrunner-logo.png'
#  custom_dir: material/overrides
  features:
#    - header.autohide
    - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.tabs.link
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
#    - navigation.path
    - navigation.expand
#    - navigation.tabs
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

use_directory_urls: false

extra:
  generator: false

watch:
  - includes

markdown_extensions:
  - admonition
  - codehilite:
      linenums: False
      guess_lang: False
  - toc:
      permalink: True
#  - markdown_fenced_code_tabs:
#      single_block_as_tab: False
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg    
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format      
  - attr_list    
  - abbr
  - footnotes


plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#7192a6"
  - glightbox:
      skip_classes:
        - skip-lightbox

